{
 "title": "ckb-pool-dashboard-v1",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pool Block Height",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sserver_last_job_broadcast_height",
     "legendFormat": "Pool Block Height"
    }
   ]
  },
  {
   "title": "CKB Node Block Height",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ckb_chain_tip_number{type=\"best_header\"}",
     "legendFormat": "Pool Block Height"
    }
   ]
  },
  {
   "title": "Authenticated Sessions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sserver_sessions_total", "legendFormat": "Authenticated Sessions" }
   ]
  },
  {
   "title": "CKB Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"CkbJob\"}",
     "legendFormat": "CKB Jobs"
    },
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"CkbRawGw\"}",
     "legendFormat": "CKB Raw Jobs"
    }
   ]
  },
  {
   "title": "CKB Share Logs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"CkbShareLog\"} ",
     "legendFormat": "CKB Share Logs"
    }
   ]
  },
  {
   "title": "CKB Solved Shares",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"CkbSolvedShare\"} ",
     "legendFormat": "CKB Solved Share"
    }
   ]
  },
  {
   "title": "Pool / CKB Node Block Height Difference",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(ckb_chain_tip_number{type=\"best_header\"} - on() sserver_last_job_broadcast_height)",
     "legendFormat": "Block Height (CKB Node - Pool)"
    }
   ]
  },
  {
   "title": "Pool Shares Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sserver_shares_per_second_since_last_scrape",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Block Height in Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sserver_last_job_broadcast_height",
     "legendFormat": "Pool Block Height"
    },
    {
     "expr": "ckb_chain_tip_number{type=\"best_header\"}",
     "legendFormat": "Chain Block Height"
    }
   ]
  },
  {
   "title": "Idle Seconds Per Last Broadcast",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sserver_idle_since_last_job_broadcast_seconds",
     "legendFormat": "Seconds Per Last Broadcast"
    }
   ]
  }
 ]
}